[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/r/*"
  to = "/.netlify/functions/r"
  status = 200

[[redirects]]
  from = "/generate"
  to = "/.netlify/functions/generate"
  status = 200
